language: android
android:
  components:
  - build-tools-19.1.0
  - android-19
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  # - extra-google-google_play_services

notifications:
  slack:
    secure: kzsIU6dTRI3tfyb7ykQi4B18LWydbyFchy0X4d1pPcY5lZ39lUz7DHI7g0NXUXvzGqqJQwkISX14UjizyIpUINidS5VjrqlT+SVRqnrsfpBIQzn17t573XgIU07s9QCxU8+XoI5EQvCn+aoZ6Tpf8XuWGzqFUvlf6LBZ07FdxFA=

before_script:
- ls -la /usr/local/android-sdk

script: "./gradlew test"
