language: android

android:
  components:
    - platform-tools
    - build-tools-19.1.0
    - android-19
    - extra
    - extra-android-support
    - extra-android-m2repository

branches:
  only:
    - dev
    - master

script: ./gradlew clean build