language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

branches:
  only:
    - dev
    - master
    
script: ./gradlew connectedAndroidTest