language: android
jdk: openjdk7
android:
  components:
    - android-19
    - platform-tools
    - build-tools-19.1.0
    - extra-android-support
    - extra-android-m2repository

  licenses:
    - '.+'

script:
  - ./gradlew clean assemble check